from collections.abc import Callable


class _BaseDocuments:
    def __init__(self, requester: Callable):
        self.requester = requester

    def create(self): ...
    def list(self): ...
    def record(self): ...
    def check_storage(self): ...
    def delete(self): ...
    def create_batch_from_csv(self): ...
    def create_batch_from_json(self): ...
